[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20.10.0", NPM_VERSION = "10.2.5" }

[context.production.environment]
  NODE_VERSION = "20.10.0"
  NPM_VERSION = "10.2.5"